### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by carstingaxion** [figuren-theater/ft-themes#26]
```[tasklist]
### Stories
- [ ] https://github.com/figuren-theater/ft-themes/issues/19
```

```[tasklist]
### Themes
- [x] [Archeo](https://wordpress.org/themes/archeo/)
- [x] [Avant-garde](https://wordpress.org/themes/avant-garde/)
- [x] [Blockbase](https://wordpress.org/themes/blockbase/)
- [x] [Blockmag](https://wordpress.org/themes/blockmag/)
- [x] [Bright-mode](https://wordpress.org/themes/bright-mode/)
- [x] [Catch-fse](https://wordpress.org/themes/catch-fse/)
- [x] [Course](https://wordpress.org/themes/course/)
- [x] [Davis-blocks](https://wordpress.org/themes/davis-blocks/)
- [x] [Loudness](https://wordpress.org/themes/loudness/)
- [x] [Miniblock-ooak](https://wordpress.org/themes/miniblock-ooak/)
- [x] [Oaknut](https://wordpress.org/themes/oaknut/)
- [x] [Ollie](https://wordpress.org/themes/ollie/)
- [x] [Pacer](https://wordpress.org/themes/pacer/)
- [x] [Pendant](https://wordpress.org/themes/pendant/)
- [x] [Poe](https://wordpress.org/themes/poe/)
- [x] [Quadrat](https://wordpress.org/themes/quadrat/)
- [x] [Riverbank](https://wordpress.org/themes/riverbank/)
- [x] [Sampler](https://wordpress.org/themes/sampler/)
- [x] [Skatepark](https://wordpress.org/themes/skatepark/)
- [x] [Twentytwenty](https://wordpress.org/themes/twentytwenty/)
- [x] [Twentytwentyone](https://wordpress.org/themes/twentytwentyone/)
- [x] [Twentytwentytwo](https://wordpress.org/themes/twentytwentytwo/)
- [x] [Twentytwentythree](https://wordpress.org/themes/twentytwentythree/)
- [x] [Twentytwentyfour](https://wordpress.org/themes/twentytwentyfour/)
- [x] [Tove](https://wordpress.org/themes/tove/)
- [x] [Wabi](https://wordpress.org/themes/wabi/)
- [x] [Wei](https://wordpress.org/themes/wei/)
```
